version: "3.8"

services:
  # The Java Backend
  backend:
    build:
      context: ./dicoogle/
      dockerfile: Dockerfile
    container_name: dicoogle-backend
    restart: unless-stopped
    ports:
      # Map host port 8080 to container port 8080 (Optional, for direct access)
      - "8080:8080"
    # Add environment variables for Dicoogle here if needed
    # environment:
    #   - SOME_VAR=some_value

  # The React Frontend (Nginx)
  frontend:
    build:
      context: ./webapp # Use the Dockerfile in the webapp folder
      dockerfile: Dockerfile
    container_name: dicoogle-frontend
    restart: unless-stopped
    ports:
      # Map host port 80 to container port 80 (Main point of entry)
      - "80:80"
    depends_on:
      - backend # Ensure backend starts before frontend
