spring:
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    pt.ua.dicooglenext: DEBUG
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    enabled: true

app:
  dimse:
    cstore:
      enabled: true
  storage:
    file-rw:
      enabled: true
      root-dir: ./data/storage
      scheme: file
    file-ro:
      root-dir: ./data/storage
  plugins:
    startup-validation:
      require-writable-provider: true
      writable-scheme: file
    storage:
      primary-scheme: file
      enabled-schemes: []
      disabled-schemes: []
  security:
    docs-enabled: true
    basic-auth:
      username: developer
      password: developer
