spring:
  config:
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.dicoogle: DEBUG
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    enabled: true

app:
  dimse:
    cfind:
      max-results: 1000
    cmove:
      max-results: 1000
    cstore:
      enabled: true
      bind-address: 127.0.0.1
      port: 6666
    query-retrieve:
      enabled: true
      bind-address: 127.0.0.1
      port: 1045
  storage:
    file-rw:
      enabled: true
      root-dir: ./data/storage
      scheme: file
    file-ro:
      root-dir: ./data/storage
  plugins:
    startup-validation:
      require-writable-provider: true
      writable-scheme: file
    storage:
      primary-scheme: file
      enabled-schemes: []
      disabled-schemes: []
  security:
    docs-enabled: true
    basic-auth-enabled: true
  users:
    seed:
      username: dicoogle
      password: dicoogle
