spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: WARN
    org.dicoogle: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  dimse:
    cfind:
    cstore:
      enabled: false
  security:
    docs-enabled: false
    basic-auth:
      username: developer
      password: developer
