spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: WARN
    org.dicoogle: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  query:
    lucene:
      auto-reindex-on-startup: false
      watch-storage: false
  dimse:
    cfind:
    cmove:
      destinations: {}
    cstore:
      enabled: false
  storage:
    file-ro:
      root-dir: ./target/test-storage/wado
    file-rw:
      enabled: false
  query:
    lucene:
      root-dir: ./target/test-index
      index-name: dicoogle-lucene
  security:
    docs-enabled: false
    basic-auth:
      username: developer
      password: developer
