services:
  legacy:
    build:
      context: .
      dockerfile: Dockerfile.legacy
    container_name: dicoogle-legacy
    ports:
      - "8080:8080"
      - "1045:1045"
      - "6666:6666"
    volumes:
      - dicoogle-storage:/dicoogle-storage

  next:
    build:
      context: .
      dockerfile: Dockerfile.next
    container_name: dicoogle-next
    depends_on:
      - legacy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8082:8082"
      - "11113:11113"
    volumes:
      - dicoogle-storage:/dicoogle-storage

volumes:
  dicoogle-storage:
