CREATE TABLE IF NOT EXISTS application_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    metadata_value VARCHAR(255) NOT NULL
);

MERGE INTO application_metadata (key, metadata_value)
KEY (key)
VALUES ('application.name', 'dicoogle-next');
