/// <reference types="vite/client" />

// Virtual module for discovered plugins (generated by vite-plugins/plugin-loader.ts)
declare module 'virtual:dicoogle-plugins' {
  export function registerAllPlugins(): void;
  export const discoveredPlugins: Array<{ id: string; name: string }>;
}
