server {
    listen 3000;

location /next/ {
        root /usr/share/nginx/html;
        
        index index.html index.htm;
        
        try_files $uri $uri/ /next/index.html;
    }

    location / {
        return 301 /next/;
    }

# WARNING: uncommnent this if you want to use a backend from outside
    
location /next/api/ {
        rewrite ^/next/api/(.*) /$1 break;
        
        proxy_pass https://demo.dicoogle.com; 

        # Headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;

        proxy_set_header Host demo.dicoogle.com;
        proxy_set_header Origin https://demo.dicoogle.com;
        proxy_set_header Referer https://demo.dicoogle.com/;

        proxy_ssl_server_name on;
    }

    # WARNING: If a backend from outside is being used comment this block

    # location /api/ {
    #     proxy_pass http://localhost:8080; 
    #
    #     rewrite ^/api/(.*) /$1 break;
    #
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection 'upgrade';
    #     proxy_cache_bypass $http_upgrade;
    #
    #     proxy_set_header Host $host;
    #
    # }
    
      location /next/files/ {
        proxy_pass http://localhost:3333; 

        # Fix the rewrite rule so it strips /next/files and passes /api/ to Express
        rewrite ^/next/files/(.*) /api/$1 break;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;

        proxy_set_header Host $host;
    }}
