/**
 * Vite Plugin Loader
 * Generates plugin manifest and loader at buildtime
 * This plugin discovers all plugins in the plugins directory and generates code to load them
 */

import { Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface PluginConfig {
  id: string;
  entry: string;
  enabled?: boolean;
  // Metadata fields
  name?: string;
  version?: string;
  description?: string;
  author?: string;
  type?: string;
  dependencies?: string[];
}

interface DiscoveredPlugin {
  id: string;
  name: string;
  path: string;
  entry: string;
  config: PluginConfig;
}

/**
 * Discover plugins by looking for plugin.config.json files
 * in the plugins directory
 */
function discoverPlugins(pluginsDir: string): DiscoveredPlugin[] {
  const discovered: DiscoveredPlugin[] = [];

  if (!fs.existsSync(pluginsDir)) {
    console.warn(`Plugins directory not found at ${pluginsDir}`);
    return discovered;
  }

  const entries = fs.readdirSync(pluginsDir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const configPath = path.join(pluginsDir, entry.name, 'plugin.config.json');

    if (fs.existsSync(configPath)) {
      try {
        const configContent = fs.readFileSync(configPath, 'utf-8');
        const config = JSON.parse(configContent) as PluginConfig;

        const pluginEntry = path.join(
          pluginsDir,
          entry.name,
          config.entry || 'index.ts'
        );

        if (fs.existsSync(pluginEntry)) {
          discovered.push({
            id: config.id || entry.name,
            name: entry.name,
            path: pluginEntry,
            entry: config.entry || 'index.ts',
            config,
          });
        } else {
          console.warn(
            `Plugin entry not found at ${pluginEntry} for plugin ${entry.name}`
          );
        }
      } catch (error) {
        console.error(
          `Error loading plugin config at ${configPath}:`,
          error
        );
      }
    }
  }

  return discovered;
}

/**
 * Generate the plugins loader code
 * This creates a virtual module that imports all discovered plugins
 */
function generatePluginLoaderCode(plugins: DiscoveredPlugin[]): string {
  let code = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by vite-plugin-loader at buildtime
 * This file imports and registers all discovered plugins
 */

import { pluginRegistry } from '@/plugin-system/registry';
`;

  // Generate imports
  plugins.forEach((plugin, index) => {
    const importPath = plugin.path.replace(/\\/g, '/');
    code += `import Plugin${index} from '${importPath}';
`;
  });

  code += `
/**
 * Register all plugins with the registry
 */
export function registerAllPlugins() {
`;

  // Generate registration code with config metadata and default enabled state
  plugins.forEach((plugin, index) => {
    const configMetadata = JSON.stringify({
      id: plugin.config.id,
      name: plugin.config.name,
      version: plugin.config.version,
      description: plugin.config.description,
      author: plugin.config.author,
      type: plugin.config.type,
      dependencies: plugin.config.dependencies,
    });

    // Default to enabled unless explicitly set to false
    const defaultEnabled = plugin.config.enabled !== false;

    code += `  try {
    // Pass config metadata and default enabled state to registry
    pluginRegistry.registerPlugin(Plugin${index}, ${configMetadata}, ${defaultEnabled});
  } catch (error) {
    console.error('Failed to register plugin ${plugin.id}:', error);
  }
`;
  });

  code += `}

/**
 * Export list of discovered plugins for debugging
 */
export const discoveredPlugins = [
`;

  plugins.forEach((plugin) => {
    code += `  { id: '${plugin.id}', name: '${plugin.name}', defaultEnabled: ${plugin.config.enabled !== false} },
`;
  });

  code += `];

export default { registerAllPlugins, discoveredPlugins };
`;

  return code;
}

/**
 * Vite Plugin for loading plugins at buildtime
 */
export function createPluginLoader(): Plugin {
  const VIRTUAL_MODULE_ID = 'virtual:dicoogle-plugins';
  const RESOLVED_VIRTUAL_MODULE_ID = `\0${VIRTUAL_MODULE_ID}`;

  let pluginsDir = '';
  let discoveredPlugins: DiscoveredPlugin[] = [];

  return {
    name: 'dicoogle-plugin-loader',

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return generatePluginLoaderCode(discoveredPlugins);
      }
    },

    configResolved(config) {
      // Resolve plugins directory relative to project root
      pluginsDir = path.resolve(config.root || process.cwd(), 'src', 'plugins');
      discoveredPlugins = discoverPlugins(pluginsDir);

      if (discoveredPlugins.length > 0) {
        console.log(`\n✓ Plugin Loader: Discovered ${discoveredPlugins.length} plugin(s)`);
        discoveredPlugins.forEach((plugin) => {
          const displayName = plugin.config.name || plugin.id;
          const version = plugin.config.version || '?';
          const enabled = plugin.config.enabled !== false ? '✓' : '✗';
          console.log(`  ${enabled} ${displayName} v${version} (${plugin.id})`);
        });
        console.log('');
      }
    },
  };
}

export default createPluginLoader;
